name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: npm install 

      
      - name: Build project
        run: npm build

      
      - name: Deploy to Amplify
        with: # Set the secret as an input
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: curl -X POST -d {} $WEBHOOK_URL -H "Content-Type:application/json"
